apiVersion: v1
kind: Service
metadata:
  name: alert-service
  namespace: group-9
  labels:
    app: alert-service
    app.kubernetes.io/name: alert-service
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
spec:
  selector:
    app: alert-service
    app.kubernetes.io/name: alert-service
    app.kubernetes.io/instance: group-9
  type: ClusterIP
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: 8083