{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ include "api-gateway.namespace" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- range .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "api-gateway.namespace" $ }}
  labels:
    {{- include "api-gateway.labels" $ | nindent 4 }}
type: {{ .type | default "Opaque" }}
stringData:
  {{- range $key, $value := .stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
