apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: budgetalert-microservices
  namespace: argocd
spec:

  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/MutagomaRaissa/budgetalert-system.git
        revision: iac
        directories:
          - path: "iac/*"
  template:
    metadata:
      name: "budgetalert-{{path.basename}}"
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: budgetalert
        app.kubernetes.io/managed-by: argocd
    spec:
      project: raissa
      source:
        repoURL: https://github.com/MutagomaRaissa/budgetalert-system.git
        targetRevision: iac
        path: "{{path}}"
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: group-9
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
