apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: budgetalert-microservices
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: budgetwatch
            chartPath: helm/budgetwatch
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: budgetwatch
        app.kubernetes.io/managed-by: argocd
    spec:
      project: raissa
      source:
        repoURL: https://github.com/MutagomaRaissa/budgetalert-system.git
        targetRevision: iac
        path: "{{chartPath}}"
        helm:
          releaseName: budgetwatch
      destination:
        server: https://kubernetes.default.svc
        namespace: group-9
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
