apiVersion: v1
kind: ConfigMap
metadata:
  name: coverage-service-config
  namespace: group-9
  labels:
    app.kubernetes.io/name: coverage-service
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://coverage-db:5432/coverage_db"
  SPRING_DATASOURCE_USERNAME: "coverage_user"
  CONSUL_HOST: "consul"
  CONSUL_PORT: "8500"
  SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS: "false"
  SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME: "coverage-service"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "admin"
  SERVER_PORT: "8082"
  SPRINGDOC_SERVER_URL: "https://130.192.100.243/group-9"
