apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
  namespace: group-9
  labels:
    app.kubernetes.io/name: consul
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
data:
  CONSUL_BIND_INTERFACE: "eth0"
  CONSUL_CLIENT_INTERFACE: "eth0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: group-9
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
data:
  RABBITMQ_DEFAULT_USER: "admin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: project-db-config
  namespace: group-9
  labels:
    app.kubernetes.io/name: project-db
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
data:
  POSTGRES_DB: "project_db"
  POSTGRES_USER: "project_user"
  PGDATA: "/var/lib/postgresql/data/pgdata"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coverage-db-config
  namespace: group-9
  labels:
    app.kubernetes.io/name: coverage-db
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
data:
  POSTGRES_DB: "coverage_db"
  POSTGRES_USER: "coverage_user"
  PGDATA: "/var/lib/postgresql/data/pgdata"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-db-config
  namespace: group-9
  labels:
    app.kubernetes.io/name: alert-db
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
data:
  POSTGRES_DB: "alert_db"
  POSTGRES_USER: "alert_user"
  PGDATA: "/var/lib/postgresql/data/pgdata"
