apiVersion: v2
name: project-db
description: Helm chart for the Budgetwatch project database
type: application
version: 0.1.0
appVersion: "15-alpine"
home: https://github.com/MutagomaRaissa/budgetalert-system
keywords:
  - budgetwatch
  - postgres
  - database
  - project-db
sources:
  - https://github.com/MutagomaRaissa/budgetalert-system
maintainers:
  - name: Budgetwatch Team
