apiVersion: v1
kind: ConfigMap
metadata:
  name: coverage-db-config
  namespace: group-9
  labels:
    app.kubernetes.io/name: coverage-db
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
data:
  POSTGRES_DB: "coverage_db"
  POSTGRES_USER: "coverage_user"
  PGDATA: "/var/lib/postgresql/data/pgdata"
