{{- $fullName := include "coverage-db.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  namespace: {{ include "coverage-db.namespace" . }}
  labels:
    {{- include "coverage-db.labels" . | nindent 4 }}
spec:
  podManagementPolicy: {{ .Values.statefulSet.podManagementPolicy }}
  revisionHistoryLimit: {{ .Values.statefulSet.revisionHistoryLimit }}
  persistentVolumeClaimRetentionPolicy:
    {{- toYaml .Values.statefulSet.persistentVolumeClaimRetentionPolicy | nindent 4 }}
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "coverage-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "coverage-db.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {{ .Values.podSecurityContext | toJson }}
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.container.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          envFrom:
            {{- range .Values.envFrom.configMaps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.envFrom.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            {{- toYaml .Values.container.volumeMounts | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.persistence.volumeClaimName }}
      spec:
        storageClassName: {{ .Values.persistence.storageClassName }}
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        volumeMode: {{ .Values.persistence.volumeMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  updateStrategy:
    {{- toYaml .Values.statefulSet.updateStrategy | nindent 4 }}
