{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ include "coverage-db.namespace" . }}
  labels:
    {{- include "coverage-db.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
