apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: group-9
  labels:
    app: project-service
    app.kubernetes.io/name: project-service
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
spec:
  selector:
    app: project-service
    app.kubernetes.io/name: project-service
    app.kubernetes.io/instance: group-9
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081