apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
  namespace: group-9
  labels:
    app.kubernetes.io/name: consul
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
data:
  CONSUL_BIND_INTERFACE: "eth0"
  CONSUL_CLIENT_INTERFACE: "eth0"
