apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: group-9
  labels:
    app: consul
    app.kubernetes.io/name: consul
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
spec:
  selector:
    app: consul
    app.kubernetes.io/name: consul
    app.kubernetes.io/instance: group-9
  ports:
    - name: http
      port: 8500
      targetPort: 8500