enabled: true
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
instanceOverride: ""
partOf: budgetwatch
imagePullSecrets: []
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
terminationGracePeriodSeconds: 30

replicaCount: 1
statefulSet:
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 10
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain

image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  tag: 3.12-management-alpine

service:
  name: rabbitmq
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP

container:
  name: rabbitmq
  ports:
    - name: amqp
      containerPort: 5672
      protocol: TCP
    - name: management
      containerPort: 15672
      protocol: TCP
  volumeMounts:
    - name: rabbitmq-data
      mountPath: /var/lib/rabbitmq

configMap:
  enabled: true
  name: rabbitmq-config
  data:
    RABBITMQ_DEFAULT_USER: admin

secret:
  enabled: true
  name: rabbitmq-secret
  type: Opaque
  stringData:
    RABBITMQ_DEFAULT_PASS: password

envFrom:
  configMaps:
    - rabbitmq-config
  secrets:
    - rabbitmq-secret

startupProbe:
  exec:
    command: ["rabbitmq-diagnostics", "-q", "ping"]
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10
  failureThreshold: 30

readinessProbe:
  exec:
    command: ["rabbitmq-diagnostics", "-q", "ping"]
  failureThreshold: 3
  initialDelaySeconds: 90
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 20

livenessProbe:
  exec:
    command: ["rabbitmq-diagnostics", "-q", "ping"]
  failureThreshold: 3
  initialDelaySeconds: 120
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 20

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

persistence:
  enabled: true
  volumeClaimName: rabbitmq-data
  mountPath: /var/lib/rabbitmq
  storageClassName: csi-cinder-fast
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  size: 5Gi
