apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: group-9
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
spec:
  selector:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: group-9
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080