apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ include "rabbitmq.namespace" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
