apiVersion: v2
name: budgetwatch
description: Umbrella chart for the Budgetwatch microservices platform
home: https://github.com/MutagomaRaissa/budgetalert-system
type: application
version: 0.1.0
appVersion: "2026.04"
keywords:
  - budgetwatch
  - microservices
  - umbrella
  - helm
sources:
  - https://github.com/MutagomaRaissa/budgetalert-system
maintainers:
  - name: Budgetwatch Team
dependencies:
  - name: alert-db
    version: 0.1.0
    condition: alert-db.enabled
  - name: alert-service
    version: 0.1.0
    condition: alert-service.enabled
  - name: api-gateway
    version: 0.1.0
    condition: api-gateway.enabled
  - name: consul
    version: 0.1.0
    condition: consul.enabled
  - name: coverage-db
    version: 0.1.0
    condition: coverage-db.enabled
  - name: coverage-service
    version: 0.1.0
    condition: coverage-service.enabled
  - name: dashboard-ui
    version: 0.1.0
    condition: dashboard-ui.enabled
  - name: networking
    version: 0.1.0
    condition: networking.enabled
  - name: project-db
    version: 0.1.0
    condition: project-db.enabled
  - name: project-service
    version: 0.1.0
    condition: project-service.enabled
  - name: rabbitmq
    version: 0.1.0
    condition: rabbitmq.enabled
