global:

  namespace: group-9

alert-db:
  enabled: true

alert-service:
  enabled: true

api-gateway:
  enabled: true

consul:
  enabled: true

coverage-db:
  enabled: true

coverage-service:
  enabled: true

dashboard-ui:
  enabled: true

networking:
  enabled: true

project-db:
  enabled: true

project-service:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

rabbitmq:
  enabled: true
