apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: group-9
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
type: Opaque
stringData:
  RABBITMQ_DEFAULT_PASS: "password"
  SPRING_RABBITMQ_PASSWORD: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: group-9
  labels:
    app.kubernetes.io/name: jwt-secret
    app.kubernetes.io/instance: group-9
    app.kubernetes.io/part-of: budgetwatch
type: Opaque
stringData:
  APP_JWT_SECRET: "budgetwatch-group9-jwt-secret-password-2026"
