{{- if .Values.jwtSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwtSecret.name }}
  namespace: {{ include "project-service.namespace" . }}
  labels:
    {{- include "project-service.labels" . | nindent 4 }}
type: {{ .Values.jwtSecret.type }}
stringData:
  {{- range $key, $value := .Values.jwtSecret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
